[package]
name = "mini_tokio"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
futures.workspace = true
crossbeam.workspace = true